baseURL: "https://eyedeekay.github.io/i2p.spec/"
languageCode: "en-us"
title: "I2P Specifications"
theme: "fresh"

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: I2P Specifications
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/i2plogo.png
    link: #
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: I2P Specifications
    # Hero subtitle (optional)
    subtitle: Detailed descriptions of I2P Data Structures and Protocols
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: i2plogo.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Contents
    sublinks:
    - title: Updates
      url: /posts/updates
    - title: Common Structures
      url: /posts/common-structures
    - title: Cryptography
      url: /posts/cryptography
    - title: Tunnel Creation
      url: /posts/tunnel-creation
    - title: Tunnel Message
      url: /posts/tunnel-message
    - title: NTCP2
      url: /posts/ntcp2
    - title: SSU
      url: /posts/ssu
    - title: Datagrams
      url: /posts/datagrams
    - title: ECIES
      url: /posts/ecies
    - title: EncryptedLeaseSet
      url: /posts/encryptedleaseset
    - title: I2CP
      url: /posts/i2cp
    - title: I2NP
      url: /posts/i2np
    - title: Streaming
      url: /posts/streaming
    - title: Filter-Format
      url: /posts/filter-format
    - title: Subscription
      url: /posts/subscription
    - title: B32 Encrypted
      url: /posts/b32encrypted
    - title: Blockfile
      url: /posts/blockfile
    - title: Configuration
      url: /posts/configuration
    - title: ECIES Routers
      url: /posts/ecies-routers
    - title: Tunnel Creation ECIES
      url: /posts/tunnel-creation-ecies
    - title: GeoIP
      url: /posts/geoip
    - title: Plugin
      url: /posts/plugin
    - title: Red25519
      url: /posts/red25519

    button: true
#  sidebar:
    # Logo (from /images/logos/___.svg)
#    logo: fresh-square
#    sections:
#    - title: User
#      icon: user
#      links:
#      - text: Profile
#        url: /
#      - text: Account
#        url: /
#      - text: Settings
#        url: /
#    - title: Messages
#      icon: envelope
#      links:
#      - text: Inbox
#        url: /
#      - text: Compose
#        url: /
#    - title: Images
#      icon: image
#      links:
#      - text: Library
#        url: /
#      - text: Upload
#        url: /
#    - title: Settings
#      icon: cog
#      links:
#      - text: User settings
#        url: /
#      - text: App settings
#        url: /
#  section1:
#    title: Great power comes
#    subtitle: with great responsibility
#    tiles:
#    - title: App builder
#      icon: mouse-globe
#      text: This is some explanatory text that is on two rows
#      url: /
#      buttonText: Free trial
#    - title: Cloud integration
#      icon: laptop-cloud
#      text: This is some explanatory text that is on two rows
#      url: /
#      buttonText: Get started
#    - title: Add-ons & plugins
#      icon: plug-cloud
#      text: This is some explanatory text that is on two rows
#      url: /
#      buttonText: Get started
#  section2:
#    title: You're here because you want the best
#    subtitle: And we know it
#    features:
#    - title: Powerful and unified interface
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      # Icon (from /images/illustrations/icons/___.svg)
#      icon: laptop-globe
#    - title: Cross-device synchronisation
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      icon: doc-sync
#    - title: Nomad system
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      icon: mobile-feed
#  section3:
#    title: One platform
#    subtitle: To rule them all
#    image: illustrations/mockups/app-mockup.png
#    buttonText: Get started
#    buttonLink: "#"
#  section4:
#    title: Our Clients love us!
#    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
#    clients:
#    - name: Irma Walters
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Accountant
#      img: 1
#    - name: John Bradley
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Financial Analyst
#      img: 2
#    - name: Gary Blackman
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: HR Manager
#      img: 3
#  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/i2p
      # Icons are from Font Awesome
      icon: github
    - link: https://github.com/i2p
      icon: dribbble
    - link: https://i2pforum.net
      icon: twitter
    - link: https://i2pgit.org/
      icon: git
    - link: https://reddit.com/r/i2p
      icon: reddit
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
